config/routes.rb
Pizza::Application.routes.draw do
   root :to => 'menus#index', :id=>1
   match '/' => 'menus#index'

   devise_scope :user do
	   get "sign_in", to: "devise/sessions#new"
	   get "sign_out", to: "devise/sessions#destroy"
   end

   match "menus/update_address" => "menus#update_address"

  devise_for :users

	match "/menus/order.:id" => 'menus#order'
	match "/menus/checkout" => 'menus#checkout'
  resources :menus

  get "order/index"

  resources :pizzas

  get "menus/order"

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :description, :image, :name, :price
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   attr_accessible :email, :password, :password_confirmation,:remember_me, :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_filter :user_logedin?, :only => "checkout"

  def user_logedin?
	  redirect_to menus_url, notice: 'Please select atleast one pizza to checkout' and return if session[:order_ids].nil?
	  redirect_to :sign_in if !user_signed_in?
  end

  def logout
	  redirect_to :sign_out
  end


  def index

    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def create
	  params[:menu]["image"] = params[:menu]["image"].tempfile.read
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end

  def order
	  (session[:order_ids].blank?) ? (session[:order_ids] = [params[:id]]) : (session[:order_ids] << params[:id] )
	  respond_to do |format|
	  	if session[:order_ids].size.eql?(0)
			format.html { redirect_to menus_url, notice: 'Failed to place an order.' }
	  	else
			format.html { redirect_to menus_url, notice: "Successfully added to cart"}
	       	end
	  end
  end

  def update_address
	  User.find(params[:id]).update_attributes!(:address => params[:addr]) 
	  session[:order_ids] = nil
	  respond_to do |format|
		  format.html { redirect_to menus_url, notice: "Successfully placed order at #{params[:addr]} by #{current_user.email}" }
		  format.json { head :no_content }
	  end   
  end

  def checkout
	  if current_user.address.nil?
	  	  @user = current_user
		  render :get_address
	  else
		  session[:order_ids]=nil
		  redirect_to menus_url, notice: "Successfully placed pick up order at #{current_user.address} by #{current_user.email}"
	  end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Pizza</title>
	<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
	<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script type="text/javascript">
	  function altRows(id){
		  if(document.getElementsByTagName){ 
			  
			  var table = document.getElementById(id);  
			  var rows = table.getElementsByTagName("tr");
			  
			  for(i = 0; i < rows.length; i++){          
				  if(i % 2 == 0){
					  rows[i].className = "evenrowcolor";
				  }else{
					  rows[i].className = "oddrowcolor";
				  }      
			  }
		  }
	  }
window.onload=function(){
	altRows('alternatecolor');
}
</script>

<style type="text/css">
	table.altrowstable {
		font-family: verdana,arial,sans-serif;
		font-size:11px;
		color:#333333;
		border-width: 1px;
		border-color: #a9c6c9;
		border-collapse: collapse;
		}
	table.altrowstable th {
		border-width: 1px;
		padding: 8px;
		border-style: solid;
		border-color: #a9c6c9;
	}
	table.altrowstable td {
		border-width: 1px;
		padding: 8px;
		border-style: solid;
		border-color: #a9c6c9;
       	}
	.oddrowcolor{
		background-color:#d4e3e5;
		}
	.evenrowcolor{
	       	background-color:#c3dde0;
		}
</style>

				
	</head>
	<body>
        	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
						<div class="container">
							<div class="navbar-header">
								<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
									<span class="sr-only">Toggle navigation</span>
									<span class="icon-bar"></span>
									<span class="icon-bar"></span>
								       	<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/menus">Pizza Online Order</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="inactive"><a href="/menus">Pizzas</a></li>
			</ul>
			<ul class="nav navbar-nav">
				<%if session[:order_ids].nil?%>
						<li class="inactive"><a href="/menus/checkout">Checkout</a></li>
					<%else%>
						<li class="inactive"><a href="/menus/checkout">Checkout (<%=session[:order_ids].size%>)</a></li>
					<%end%>
			</ul>
			<ul class="nav navbar-nav">
			<%if user_signed_in?%>
				<li class="inactive"><a href="/sign_out">Logout</a></li>
			<%else%>
				<li class="inactive"><a href="/sign_in">Login</a></li>
			<%end%>
			</ul>
	</div>
</div>
</nav>
<div class="container">
	       <p id="notice"><%= notice %></p>
	              <p id="alert"><%= alert %></p>
	<%= yield %>
</div>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>

</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price%><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>
</br>
<%= link_to 'Show', @menu %> |
<%= link_to 'Menu', menus_path %>

app/views/menus/get_address.html.erb
<span>User Name</span><%=@user.email%>

<%= form_tag({:controller => "menus", :action => "update_address", :id => @user.id}, :multipart => true) do %>
  <div class="field">
    <%= label_tag "User Name"%><br />
    <%= text_field_tag :name, @user.email, :disabled => true %>
  </div>
  <div class="field">
    <%= label_tag "Address"%><br />
    <%= text_field_tag :addr%>
  </div>
<%= submit_tag 'Submit', :class=> "btn" %>
 <% end %>

app/views/menus/index.html.erb
<table class="altrowstable" id="alternatecolor" style="width:100%;height:50px;">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @menus.each do |menu| %>
  <tr>
    <%filename = "pizza_#{rand(999)}"%>
    <%File.open("#{Rails.root}/app/assets/images/#{filename}", 'wb') do|f|
      f.write(menu.image)
    end%>
    <td><%= image_tag("#{filename}",:width => "160")%></td>
    <td><%=menu.name%></td>
    <td><%=menu.description%></td>
    <td>Rs <%= menu.price rescue 210 %></td>
    <td><%= link_to 'Add to cart', menus_order_path(menu) %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<br />

<%= button_to 'Add Pizza', new_menu_path, :method => "get"%> 

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<table style="width:80%;height:60px">
	<tr>
		<th>
			Name
		</th>
		<td>:</td>
		<td>
			<%= @menu.name %>
		</td>
	</tr>
	<tr>
		<th>
			Description
		</th>
		<td>:</td>
		<td>
			<%= @menu.description %>
		</td>
	</tr>
	<tr>
		<th>
			Image
		</th>
		<td>:</td>
		<td>
			<%filename = "pizza_#{rand(999)}"%>
			<%File.open("#{Rails.root}/app/assets/images/#{filename}", 'wb') do|f|
				f.write(@menu.image)
			end%>
		       	<%= image_tag("#{filename}",:width => "160")%>
		</td>
	</tr>
	<tr>
		<th>
			Price
		</th>
		<td>:</td>
		<td>
			<%= @menu.price%>
		</td>
	</tr>
</table>
</br>
</br>
<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Menu', menus_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>